# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: BlogBox

# Below the site title
tagline: Tales of a digital nomad.

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: |
  BlogBox is a bold theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net.

# The base hostname & protocol of your site for where absolute urls are needed
url: https://blogbox.netlify.app

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: Archives
  url: /tags/
- text: Style Guide
  url: /style-guide/
- text: About
  url: /about/

# Author information - author info at the bottom of the post
author_name: "å°å­™å’Œå°æçš„çˆ±æƒ…ğŸ›–"
author_bio: "è¿™é‡Œæ˜¯å°å­™å’Œå°æçš„æ‹çˆ±å°å±‹ğŸ›–ï¼Œåœ¨æ­¤è®°å½•ç€äºŒäººçš„ç‚¹ç‚¹æ»´æ»´ã€‚ç›¸çŸ¥ä¸æ˜“ï¼Œç›¸å®ˆæ›´éš¾ï¼Œæˆ‘ä»¬æ˜¯å¹¸è¿çš„ï¼Œé‡åˆ°äº†åŒå‘å¥”èµ´çš„çˆ±æƒ…ï¼Œç»å†äº†ç”œèœœã€è€ƒéªŒï¼Œå¾€åä½™ç”Ÿï¼Œå…±åŒå®ˆæŠ¤!!!"
author_url: "https://520snow.github.com"
author_location: "Beijing, China"
author_image: authorimage.jpg

# Footer ad banner
banner_image: banner.jpg
banner_url: https://520snow.github.com/

# Footer newsletter widget - add your form action url for MailChimp signup form here
# é‚®ä»¶å‘é€åœ°å€
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "username"
facebook_username: "username"
github_username: "username"
codepen_username: "username"
dribbble_username: "username"
medium_username: "@username"
instagram_username: "username"
pinterest_username: "username"
linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
